# Script teste para agrupamento de dados de rede

O objetivo do script é possibilitar que dados de capacidade de interconexão sejam agregados em subsistemas. Para isso, é feito a leitura do arquivo gerado pelos scripts do pypsa-brazil

In [27]:
import pandas as pd
import numpy as np

In [28]:
path = "C:\\TCC\\ScriptsPypsaBrazil\\open-brazilian-energy-data_atualizado\\grid\\results\\EPEWebmap_equivalent_grid_aggregate_by_state_operation_and_planed.csv"
grid = pd.read_csv(path)
grid.head()

,Unnamed: 0,node0,node1,transfer_capacity,efficiency,name,length,carrier
0,0,AC,RO,694.424749,0.997181,"LT 230 kV Abunã - Rio Branco I, C2_LT 230 kV A...",304.879878,ac
1,1,AL,BA,9740.762028,0.998153,LT 230 kV Paulo Afonso III - UHE Paulo Afonso ...,31.629925,ac
2,2,AL,PE,6690.456467,0.997816,LT 230 kV Garanhuns II - Paulo Afonso III C3_L...,134.432276,ac
3,3,AL,SE,9677.314272,0.998663,LT 500 kV UHE Xingó - Xingó C4_LT 230 kV Paulo...,69.919940,ac
4,4,AM,PA,2650.803484,0.999133,"LT 500 kV Oriximiná - Silves, C1_LT 500 kV Ori...",255.321517,ac

In [29]:
regiao_estado ={'PA': 'NORTE',
                'TO': 'NORTE',
                'MA': 'NORTE',
                'AP': 'NORTE',
                'AM': 'NORTE',
                'RR': 'NORTE',
                'PI': 'NORDESTE',
                'CE': 'NORDESTE',
                'RN': 'NORDESTE',
                'PB': 'NORDESTE',
                'PE': 'NORDESTE',
                'AL': 'NORDESTE',
                'SE': 'NORDESTE',
                'BA': 'NORDESTE',
                'ES': 'SUDESTE',
                'RJ': 'SUDESTE',
                'MG': 'SUDESTE',
                'SP': 'SUDESTE',
                'GO': 'SUDESTE',
                'DF': 'SUDESTE',
                'MT': 'SUDESTE',
                'AC': 'SUDESTE',
                'RO': 'SUDESTE',
                'MS': 'SUDESTE',
                'RS': 'SUL',
                'SC': 'SUL',
                'PR': 'SUL',
                'ARG': 'ARGENTINA',
                'PRY': 'PARAGUAI',
                'VEN': 'VENEZUELA',
                'URY': 'URUGUAI'}

print(regiao_estado)

{'PA': 'NORTE', 'TO': 'NORTE', 'MA': 'NORTE', 'AP': 'NORTE', 'AM': 'NORTE', 'RR': 'NORTE', 'PI': 'NORDESTE', 'CE': 'NORDESTE', 'RN': 'NORDESTE', 'PB': 'NORDESTE', 'PE': 'NORDESTE', 'AL': 'NORDESTE', 'SE': 'NORDESTE', 'BA': 'NORDESTE', 'ES': 'SUDESTE', 'RJ': 'SUDESTE', 'MG': 'SUDESTE', 'SP': 'SUDESTE', 'GO': 'SUDESTE', 'DF': 'SUDESTE', 'MT': 'SUDESTE', 'AC': 'SUDESTE', 'RO': 'SUDESTE', 'MS': 'SUDESTE', 'RS': 'SUL', 'SC': 'SUL', 'PR': 'SUL', 'ARG': 'ARGENTINA', 'PRY': 'PARAGUAI', 'VEN': 'VENEZUELA', 'URY': 'URUGUAI'}

In [30]:

grid = grid.drop(columns=["name", "length", "carrier"])
grid.head()

   Unnamed: 0 node0 node1  transfer_capacity  efficiency
0           0    AC    RO         694.424749    0.997181
1           1    AL    BA        9740.762028    0.998153
2           2    AL    PE        6690.456467    0.997816
3           3    AL    SE        9677.314272    0.998663
4           4    AM    PA        2650.803484    0.999133

In [31]:
grid["regiao0"] = grid["node0"].map(regiao_estado)
grid["regiao1"] = grid["node1"].map(regiao_estado)
grid.head()

   Unnamed: 0 node0 node1  transfer_capacity  efficiency   regiao0   regiao1
0           0    AC    RO         694.424749    0.997181   SUDESTE   SUDESTE
1           1    AL    BA        9740.762028    0.998153  NORDESTE  NORDESTE
2           2    AL    PE        6690.456467    0.997816  NORDESTE  NORDESTE
3           3    AL    SE        9677.314272    0.998663  NORDESTE  NORDESTE
4           4    AM    PA        2650.803484    0.999133     NORTE     NORTE

In [34]:
regioes_brasil = ['SUDESTE', 'SUL', 'NORDESTE', 'NORTE']
grid_subsistema = pd.DataFrame(columns = ['regiao0', 'regiao1', 'transfer_capacity', 'efficiency'])
for regiao0 in regioes_brasil:
    regioes_total = ['SUDESTE', 'SUL', 'NORDESTE', 'NORTE', 'ARGENTINA','PARAGUAI','VENEZUELA', 'URUGUAI']
    regioes_total.remove(regiao0)
    for regiao1 in regioes_total:
        grid_regiao = grid[(grid['regiao0'] == regiao0 & grid['regiao1'] == regiao1) or
                           (grid['regiao0'] == regiao1 & grid['regiao1'] == regiao0)]
        if not grid_regiao.empty:
            transfer_capacity = grid_regiao['transfer_capacity'].sum()
            efficiency = np.average(df['efficiency'], weights=df['transfer_capacity'])
            grid_subsistema = grid_subsistema.append({'regiao0': regiao0,
                                                      'regiao1': regiao1,
                                                      'transfer_capacity': transfer_capacity,
                                                      'efficiency': efficiency})

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [45]:
dict_test = {'regiao0': 'SUDESTE','regiao1': 'SUL','transfer_capacity': 10,'efficiency': 1}
dict_test_df = pd.DataFrame(dict_test, index=[0])
dict_test_df.head()

   regiao0 regiao1  transfer_capacity  efficiency
0  SUDESTE     SUL                 10           1

In [41]:
test = pd.DataFrame(columns = ['regiao0', 'regiao1', 'transfer_capacity', 'efficiency'])
dict_test = {'regiao0': 'SUDESTE','regiao1': 'SUL','transfer_capacity': 10,'efficiency': 1}
pd.concat([test, pd.DataFrame(dict_test, index=[0])])

ValueError: If using all scalar values, you must pass an index